# Generated by Django 5.1.1 on 2024-10-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_funneldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('user_type', models.CharField(choices=[('Startup', 'Startup'), ('Enterprise', 'Enterprise')], max_length=10)),
                ('session_duration', models.FloatField()),
            ],
        ),
    ]
